#===========================================================================
# allowed DPIs
#===========================================================================
dpis:
  - 254
  - 190
  - 127
  - 56

#===========================================================================
# allowed Formats
#===========================================================================
# '*' means any formats
formats: ['*']

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000
  - 8000000
  - 16000000
  - 32000000
  - 64000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: www.camptocamp.org
  - !ipMatch
    ip: ows.terrestris.de
  - !ipMatch
    ip: gis.kademo.nl
  - !ipMatch
    ip: suite.opengeo.org
  - !ipMatch
    ip: www2.demis.nl
  - !ipMatch
    ip: data.fao.org
  - !ipMatch
    ip: geodata.nationaalgeoregister.nl
  - !dnsMatch
    host: demo.mapfish.org
    port: 80

# the default fileName for the files downloaded from the servlet
outputFilename: MapFish_PrintOut

layouts:
  #===========================================================================
  A4 portrait:
  #===========================================================================
    # override the default outputFileName defined above
#    outputFilename: A4_Layout
    mainPage:
      rotation: true
      pageSize: A4
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 24
            align: center
            text: '${mapTitle}'
      items:
        - !map
          spacingAfter: 30
          width: 440
          height: 483
        - !text
          text: '${comment}'
          spacingAfter: 30
      footer:
        height: 30
        items:
          - !columns
            items:
              - !text
                backgroundColor: #eeeeee
                align: left
                text: Mapfish Printing Demo
              - !text
                align: right
                text: 'Page ${pageNum}'
